### ISSUE TITLE
Invalid Package Name

### ISSUE THREAD

**Issue by sno2** [AbhayAysola/tnb-go#3]
I think that we had thought that doing `package account` would just affect the single file, because you are supposed to have a single package name within the entire library.  If you checkout the [docs for this package on pkg.go.dev](https://pkg.go.dev/github.com/AbhayAysola/tnb-go), then you can see that it is aliasing it as `account` due to this.  Therefore, we should rename the `package account` instances to a singular package name for the entire package such as `tnb_go`.

**Comment by AbhayAysola** [comment]
I also noticed that and I was thinking of waiting until I add another package to see how that will work. If it's still the same way, I might have to refactor the packages into their own folders. I'd rather not have everything inside a single package. Thanks for the suggestion though.

**Comment by AbhayAysola** [comment]
@sno2 fixed this in https://github.com/AbhayAysola/tnb-go/commit/65e66d01fd8612f4c60381dfcdafb5099e4e70ce
